# This is a basic workflow to help you get started with Actions

name: Yaml run

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    name: Prepare installation
    steps:
        
      - name: "Checkout the repository"
        uses: actions/checkout@v2
        with:
          path: ${{ github.actor }}

      - name: "Create the user working directory"
        run: |
          mkdir -p ${{ github.workspace }}/${{ github.actor }}
      - name: "Check yml"
        env:
          ANSIBLE_FORCE_COLOR: '1'
        run: |
         cd ${{ github.workspace }}/${{ github.actor }}/AnsibleTest.yml
